#!/bin/bash

echo 'test' > /home/ec2-user/user-script-output.txt
sudo yum install -y wget 
sudo adduser --quiet --disabled-password --shell /bin/bash --home /var/lib/jenkins-slave --gecos "jenkins" jenkins
sudo echo "jenkins:#jenkins1" | chpasswd

#sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo 
#sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key 
#sudo yum install -y jenkins java 
sudo yum install -y java
#sudo service jenkins start 
#i=0
#while [ $i -lt 10 ];
#do
#if [ -e /dev/xvdb ]
#then
#  sudo mount /dev/xvdb /var/lib/jenkins
#  break
#else
#  sleep 30
#  let i=i+1
#fi
#done

#mkdir /var/lib/jenkins/.ssh
#chown jenkins.jenkins /var/lib/jenkins/.ssh
#sudo -u jenkins -H ssh-keygen

